apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "87.16.1"
    helm:
      values: |
        prometheus:
          prometheusSpec:
            enableFeatures:
              - exemplar-storage
        grafana:
          adminPassword: Lab010203
          deleteDatasources:
            - name: Tempo
              orgId: 1
          persistence:
            enabled: true
          additionalDataSources:
            - name: Tempo
              type: tempo
              uid: tempo
              access: proxy
              url: http://tempo.monitoring.svc.cluster.local:3200
              jsonData:
                httpMethod: GET
                streamingEnabled:
                  search: false
                  metrics: false
          sidecar:
            datasources:
              exemplarTraceIdDestinations:
                datasourceUid: tempo
                traceIdLabelName: trace_id
                urlDisplayLabel: Ver trace
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true